name: run-tests

on:
  pull_request:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

    - name: Cache Tox
      id: cache-tox
      uses: actions/cache@v3
      with:
        path: ~/.tox
        key: tox

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install tox
        run: pip install tox
        shell: bash

      - name: Run tests
        run: tox
        shell: bash
